/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import config.conexion;
import controler.rol;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pc_Estiven
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    conexion conDavid = new conexion();

    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;

    public principal() {
        initComponents();
        Listar();
        ComboDavid.addItem("Seleccionar...");
        RellenarCombo();
        PanelInformacion.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        PanelBusqueda = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BtnConsultar = new javax.swing.JButton();
        BtnLimpiar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TxtBuscarNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        PanelListaUser = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaUser = new javax.swing.JTable();
        BtnCrear = new javax.swing.JButton();
        PanelInformacion = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        BtnGuardar = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxtId = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        SiRadioButton = new javax.swing.JRadioButton();
        NoRadioButton = new javax.swing.JRadioButton();
        ComboDavid = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 105, 116));

        PanelBusqueda.setBackground(new java.awt.Color(21, 218, 218));

        jLabel2.setText("Parametros de Busqueda");

        BtnConsultar.setText("Consultar");

        BtnLimpiar.setText("Limpiar");

        jLabel3.setText("Nombre");

        TxtBuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBuscarNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBusquedaLayout = new javax.swing.GroupLayout(PanelBusqueda);
        PanelBusqueda.setLayout(PanelBusquedaLayout);
        PanelBusquedaLayout.setHorizontalGroup(
            PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelBusquedaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnConsultar))
                        .addGap(33, 33, 33)
                        .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnLimpiar)
                            .addComponent(TxtBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelBusquedaLayout.setVerticalGroup(
            PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnConsultar)
                    .addComponent(BtnLimpiar))
                .addGap(18, 18, 18)
                .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel1.setText("Gestion de Usuario");

        PanelListaUser.setBackground(new java.awt.Color(191, 181, 181));

        jLabel4.setText("Lista de Usuarios");

        TablaUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id User", "Id Rol", "Nombre Rol", "Nombre", "Activo"
            }
        ));
        TablaUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaUserMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(TablaUser);

        BtnCrear.setText("Crear");
        BtnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelListaUserLayout = new javax.swing.GroupLayout(PanelListaUser);
        PanelListaUser.setLayout(PanelListaUserLayout);
        PanelListaUserLayout.setHorizontalGroup(
            PanelListaUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListaUserLayout.createSequentialGroup()
                .addGroup(PanelListaUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelListaUserLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(BtnCrear))
                    .addGroup(PanelListaUserLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        PanelListaUserLayout.setVerticalGroup(
            PanelListaUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListaUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelListaUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(BtnCrear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelInformacion.setBackground(new java.awt.Color(125, 215, 151));

        jLabel5.setText("Informacion del Usuario");

        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        BtnEditar.setText("Editar");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        jLabel6.setText("ID");

        jLabel7.setText("Nombre");

        jLabel8.setText("Rol");

        jLabel9.setText("Activo");

        TxtId.setEditable(false);
        TxtId.setEnabled(false);

        SiRadioButton.setText("Si");
        SiRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SiRadioButtonMouseClicked(evt);
            }
        });
        SiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiRadioButtonActionPerformed(evt);
            }
        });

        NoRadioButton.setText("No");
        NoRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NoRadioButtonMouseClicked(evt);
            }
        });

        ComboDavid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboDavidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelInformacionLayout = new javax.swing.GroupLayout(PanelInformacion);
        PanelInformacion.setLayout(PanelInformacionLayout);
        PanelInformacionLayout.setHorizontalGroup(
            PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInformacionLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelInformacionLayout.createSequentialGroup()
                        .addComponent(BtnGuardar)
                        .addGap(26, 26, 26)
                        .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelInformacionLayout.createSequentialGroup()
                                .addComponent(BtnEditar)
                                .addGap(30, 30, 30)
                                .addComponent(BtnEliminar))
                            .addComponent(TxtId, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtNombre)))
                    .addGroup(PanelInformacionLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelInformacionLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(SiRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(NoRadioButton))
                            .addGroup(PanelInformacionLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(ComboDavid, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        PanelInformacionLayout.setVerticalGroup(
            PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardar)
                    .addComponent(BtnEditar)
                    .addComponent(BtnEliminar))
                .addGap(18, 18, 18)
                .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ComboDavid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(SiRadioButton)
                    .addComponent(NoRadioButton))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PanelBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(PanelListaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(PanelInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelListaUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtBuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBuscarNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBuscarNombreActionPerformed

    private void SiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SiRadioButtonActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        Guardar();
        Limpiar();
        Listar();
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void ComboDavidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboDavidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboDavidActionPerformed

    private void TablaUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaUserMouseClicked
        PanelInformacion.setVisible(true);
        BtnGuardar.setVisible(false);
        BtnEditar.setVisible(true);
        BtnEliminar.setVisible(true);
        
        int fila = TablaUser.getSelectedRow();
        int idusuario = Integer.parseInt((String) TablaUser.getValueAt(fila, 0).toString());
        int idrol = Integer.parseInt((String) TablaUser.getValueAt(fila, 1).toString());
        String nombrerol = (String) TablaUser.getValueAt(fila, 2);
        String nombre = (String) TablaUser.getValueAt(fila, 3);
        String activo = (String) TablaUser.getValueAt(fila, 4);

        TxtId.setText("" + idusuario);
        TxtNombre.setText("" + nombre);
        ComboDavid.removeAllItems();
        ComboDavid.addItem(new rol(idrol, nombrerol));
        RellenarCombo();
        if ("Si".equals(activo)) {
            SiRadioButton.setSelected(true);
            NoRadioButton.setSelected(false);
        } else {
            NoRadioButton.setSelected(true);
            SiRadioButton.setSelected(false);
        }

    }//GEN-LAST:event_TablaUserMouseClicked

    private void BtnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearActionPerformed
        PanelInformacion.setVisible(true);
        BtnCrear.setVisible(true);   
        BtnGuardar.setVisible(true); 
        BtnEditar.setVisible(false);
        BtnEliminar.setVisible(false);
       Limpiar();
    }//GEN-LAST:event_BtnCrearActionPerformed

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        Editar();
        Limpiar();
        limpiarTabla();
        Listar();
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void SiRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SiRadioButtonMouseClicked
        NoRadioButton.setSelected(false);
    }//GEN-LAST:event_SiRadioButtonMouseClicked

    private void NoRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoRadioButtonMouseClicked
        SiRadioButton.setSelected(false);
    }//GEN-LAST:event_NoRadioButtonMouseClicked

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        
        Eliminar();
        Limpiar();
        limpiarTabla();
        Listar();
    }//GEN-LAST:event_BtnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    void Listar() {
        String sql = "SELECT usuario.ID_USUARIO, rol.ID_ROL, rol.NOMBRE, usuario.NOMBRE,"
                + "usuario.ACTIVO FROM usuario inner join rol on rol.ID_ROL = usuario.ID_ROL order by ID_USUARIO asc";
        try {
            cn = conDavid.ConexionDavid();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            Object[] usuario = new Object[5];
            modelo = (DefaultTableModel) TablaUser.getModel();
            while (rs.next()) {
                usuario[0] = rs.getInt("ID_USUARIO");
                usuario[1] = rs.getString("rol.ID_ROL");
                usuario[2] = rs.getString("rol.NOMBRE");
                usuario[3] = rs.getString("usuario.NOMBRE");
                usuario[4] = rs.getString("ACTIVO");
                modelo.addRow(usuario);
            }
            TablaUser.setModel(modelo);
            cn.close();
        } catch (Exception e) {
            System.err.print(e.toString());
        }
    }

    void Editar() {

        int fila = TablaUser.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Usuario no seleccionado");
        } else {
            int idusuario = Integer.parseInt((TxtId.getText()));
            int idrolnuevo = ComboDavid.getSelectedIndex();
            //Error de rol= 0 obvio no esta en la base de datos cuando es administrador
            System.out.println(idrolnuevo);
            System.out.println(idrolnuevo);
            System.out.println(idrolnuevo);
            System.out.println(idrolnuevo);
            String nombrenuevo = TxtNombre.getText();

            String activonuevo = "";
            if (SiRadioButton.isSelected() == true) {
                activonuevo = "Si";
            }
            if (NoRadioButton.isSelected() == true) {
                activonuevo = "No";
            }

            Actualizar(idusuario, idrolnuevo, nombrenuevo, activonuevo);
        }
    }

    void Actualizar(int idusuario, int idrol, String nombre, String activo) {

        try {
            String sql = "update Usuario set ID_ROL='" + idrol + "',NOMBRE='" + nombre + "',ACTIVO='" + activo + "' where ID_USUARIO=" + idusuario;
            cn = conDavid.ConexionDavid();
            st = cn.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Usuario Actualizado !!!");
            cn.close();
        } catch (Exception e) {
            System.err.print(e.toString());
        }
    }

    void RellenarCombo() {
        
        try {
            cn = conDavid.ConexionDavid();
            String scriptbd = "select ID_ROL,NOMBRE from ROL";
            st = cn.createStatement();
            rs = st.executeQuery(scriptbd);
            ResultSet rs = st.executeQuery(scriptbd);

            while (rs.next()) {
                ComboDavid.addItem(new rol(rs.getInt("ID_ROL"), rs.getString("NOMBRE")));
            }

            cn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error" + e.toString());
        }

    }

    void Eliminar() {
        
        int idusuario = Integer.parseInt((TxtId.getText()));
        
        try {
            cn = conDavid.ConexionDavid();
            String sql = "delete from USUARIO where ID_USUARIO=" + idusuario;
            st = cn.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Usuario Eliminado !!!");
            cn.close();
            st.close();     
        } catch (SQLException e) {
        }
        
    }

    void limpiarTabla() {
        for (int i = 0; i<TablaUser.getRowCount(); i++) {
            modelo.removeRow(i);
            i-=1;
        }
    }

    void Guardar() {
        String nombre = TxtNombre.getText();
        int rol = ComboDavid.getSelectedIndex();
        String activo = "";

        if (SiRadioButton.isSelected() == true) {
            activo = "Si";
        }
        if (NoRadioButton.isSelected() == true) {
            activo = "No";
        }

        if (nombre.equals("") || activo.equals("") || rol == 0) {
            JOptionPane.showMessageDialog(null, "Datos vacios !!!");
        } else {
            try {
                String sql = "insert into USUARIO(ID_ROL,NOMBRE,ACTIVO)values('" + rol + "','" + nombre + "','" + activo + "')";
                cn = conDavid.ConexionDavid();
                st = cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Usuario Agregado !!!");
                limpiarTabla();
            } catch (Exception e) {
            }
        }

    }

    void Limpiar() {

        TxtId.setText("");
        TxtNombre.setText("");
        ComboDavid.setSelectedItem(null);
        SiRadioButton.setSelected(false);
        NoRadioButton.setSelected(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConsultar;
    private javax.swing.JButton BtnCrear;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnLimpiar;
    private javax.swing.JComboBox<Object> ComboDavid;
    private javax.swing.JRadioButton NoRadioButton;
    private javax.swing.JPanel PanelBusqueda;
    private javax.swing.JPanel PanelInformacion;
    private javax.swing.JPanel PanelListaUser;
    private javax.swing.JRadioButton SiRadioButton;
    private javax.swing.JTable TablaUser;
    private javax.swing.JTextField TxtBuscarNombre;
    private javax.swing.JTextField TxtId;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
